<?php 
return [
    // 'short' => [
    //     '1' => 'jan',
    //     '2' => 'feb',
    //     '3' => 'mar',
    //     '4' => 'apr',
    //     '5' => 'may',
    //     '6' => 'jun',
    //     '7' => 'jul',
    //     '8' => 'aug',
    //     '9' => 'sep',
    //     '10' => 'oct',
    //     '11' => 'nov',
    //     '12' => 'dec',
    // ],
    // 'long' => [
        '1' => 'january',
        '2' => 'february',
        '3' => 'march',
        '4' => 'april',
        '5' => 'may',
        '6' => 'june',
        '7' => 'july',
        '8' => 'august',
        '9' => 'september',
        '10' => 'october',
        '11' => 'november',
        '12' => 'december',
    // ],
];