<?php 
return [
	'new' => 'New',
    'approved' => 'Approved', 
    'pending' => 'Suspicious', 
    'rejected' => 'Rejected',
    'test' => 'Test',
    'added_new' => 'Added New',
    'added_approved' => 'Added Approved',
    'added_rejected' => 'Added Rejected',
    'admin_imported' => 'Imported by Admin',
    'added_by_clinic_claimed' => 'Added by Clinic Claimed',
    'added_by_clinic_unclaimed' => 'Added by Clinic Approved',
    'added_by_clinic_new' => 'Added by Clinic New',
    'added_by_clinic_rejected' => 'Added by Clinic Rejected',
    'dentist_no_email' => 'Dentist No Email',
    'added_by_dentist_claimed' => 'Added by Dentist Claimed',
    'added_by_dentist_unclaimed' => 'Added by Dentist Approved',
    'added_by_dentist_new' => 'Added by Dentist New',
    'added_by_dentist_rejected' => 'Added by Dentist Rejected',
    'duplicated_email' => 'Duplicated Email',
    'clinic_branch' => 'Clinic Branch',
];