<?php 
return [
	'new' => 'info',
    'approved' => 'success', 
    'pending' => 'warning', 
    'rejected' => 'danger',
    'test' => 'default',
    'added_new' => 'info',
    'added_approved' => 'success',
    'added_rejected' => 'danger',
    'admin_imported' => 'info',
    'added_by_clinic_claimed' => 'success',
    'added_by_clinic_unclaimed' => 'success',
    'added_by_clinic_new' => 'info',
    'added_by_clinic_rejected' => 'danger',
    'dentist_no_email' => 'success',
    'added_by_dentist_claimed' => 'success',
    'added_by_dentist_unclaimed' => 'success',
    'added_by_dentist_new' => 'info',
    'added_by_dentist_rejected' => 'danger',
    'duplicated_email' => 'danger',
    'old_verified_no_kyc' => 'info',
    'old_verified_no_sc' => 'info', 
    'new_verified' => 'success', 
    'new_not_verified' => 'info',
    'suspicious_badip' => 'warning',
    'suspicious_admin' => 'warning',
    'self_deleted' => 'danger',
    'deleted' => 'danger',
];